### ISSUE TITLE
Language checker issue

### ISSUE THREAD

**Issue by brandonskerritt** [brandonskerritt/Ciphey#12]

**Comment by brandonskerritt** [comment]
python3 main.py -t "hello"
Traceback (most recent call last):
  File "main.py", line 230, in <module>
    cipherObj = Ciphey(args['text'], cipher)
  File "main.py", line 25, in __init__
    self.lc = LanguageChecker()
TypeError: 'module' object is not callable

**Comment by brandonskerritt** [comment]
Fixed issue in 90ed7ec06271382ab30f0fe7cfb6715989dcf49b
